Algoritmo "CalculoProcedimento"

Var
   T,n:inteiro
Procedimento Calculo(var A,B:inteiro)
inicio
      B <- B + A
fimprocedimento

Inicio
      T <- 0
      enquanto n <> 1111 faca
               escrevaL("Dgite um numero: ")
               leia (n)
               se n <> 1111 entao
                  Calculo(n,T)
               fimse
      fimenquanto
      escrevaL("Somando todos o numeros da",T)
      
      

Fimalgoritmo