Algoritmo "SomaParamentrosReferencia"

Var
   N1,N2:inteiro
Procedimento soma(var A,B:inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escrevaL("Valor de A =",A)
      escrevaL("Valor de B =",B)
      escrevaL("Valor de A + B =",A+B)
      
fimprocedimento

Inicio
      N1 <- 4
      N2 <- 8
      soma(N1,N2)
      EscrevaL("Valor de N1 =",N1)
      escrevaL("Valor de N2 =",N2)

Fimalgoritmo